gnn:
  gripper_sym_rod: gripper_sym_rod_robot_v4_surf_nocorr_full_normal/dy_keyframe_nr=0.01_tnr=0.005_0.005_his=1_seq=2_time_step=3_chamfer_emd_0.5_0.5_rm=1_valid_Oct-19-17:27:26
learned:
  gripper_sym_rod: 
  - gripper_sym_rod_robot_v4_surf_nocorr_full_normal_keyframe=16_action=2_p=300/plan_p=300_n=1_ef=1_normal=1_weight=1.0+1.0_bin=64+8_rot=0.25_ratio=0.1
  - gripper_sym_rod_robot_v4_surf_nocorr_full_normal_keyframe=16_action=2_p=300/plan_p=300_n=2_ef=1_normal=1_weight=1.0+1.0_bin=32+8_rot=0.25_ratio=0.1